<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Test Page</title>
    
    </head>
    <body>
<h1>This is the H1 heading</h1>
<?php
echo "Some content generated by PHP";
?>
        <h3>A H3 heading</h3>
        <h4>A h4 heading</h4>
    </body>
</html>
